### ISSUE TITLE
goroutine leak after recover and close

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/amqpx#2]
This test leaks two goroutines:
https://github.com/jxsl13/amqpx/blob/main/pool/connection_test.go#L44-L61

Basic test procedure: 
- connect to rabbitmq through toxiproxy: https://github.com/jxsl13/amqpx/blob/main/pool/connection.go#L96
- kill connection via toxiproxy: https://github.com/jxsl13/amqpx/blob/ee6619b9a4047e6eb914b746f566f50bf7e31fe4/pool/toxiproxy_client_test.go#L34-L57
- reconnect toxiproxy to rabbitmq after a while
- trigger a connection recovery: https://github.com/jxsl13/amqpx/blob/main/pool/connection.go#L279-L333
- close the connetion

```
Running tool: /usr/local/bin/go test -timeout 1m -run ^TestNewConnectionDisconnect$ github.com/jxsl13/amqpx/pool -trace=trace.out -v -count=1 -race

=== RUN   TestNewConnectionDisconnect
    /Users/john/Development/amqpx/pool/connection.go:374: level=debug, msg=connecting..., connection=TestNewConnection
    /Users/john/Development/amqpx/pool/connection.go:366: level=info, msg=connected, connection=TestNewConnection
    /Users/john/Development/amqpx/pool/toxiproxy_client_test.go:41: level=debug, msg=disabled rabbitmq connection,
    /Users/john/Development/amqpx/pool/connection.go:366: level=info, msg=recovering, connection=TestNewConnection
    /Users/john/Development/amqpx/pool/connection.go:374: level=debug, msg=connecting..., connection=TestNewConnection
    /Users/john/Development/amqpx/pool/toxiproxy_client_test.go:48: level=debug, msg=enabled rabbitmq connection,
    /Users/john/Development/amqpx/pool/connection.go:374: level=debug, msg=connecting..., connection=TestNewConnection
    /Users/john/Development/amqpx/pool/connection.go:366: level=info, msg=connected, connection=TestNewConnection
    /Users/john/Development/amqpx/pool/connection.go:366: level=info, msg=recovered, connection=TestNewConnection
    /Users/john/Development/amqpx/pool/connection.go:374: level=debug, msg=closing..., connection=TestNewConnection
    /Users/john/Development/amqpx/pool/connection.go:366: level=info, msg=closed, connection=TestNewConnection
--- PASS: TestNewConnectionDisconnect (4.25s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 25 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x272ded8, 0x72)
	/usr/local/Cellar/go/1.18/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000240198, 0xc00012c000?, 0x0)
	/usr/local/Cellar/go/1.18/libexec/src/internal/poll/fd_poll_runtime.go:83 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000240180, {0xc00012c000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18/libexec/src/internal/poll/fd_unix.go:167 +0x415
net.(*netFD).Read(0xc000240180, {0xc00012c000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18/libexec/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc0000a6070, {0xc00012c000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18/libexec/src/net/net.go:183 +0xb1
net/http.(*persistConn).Read(0xc0002185a0, {0xc00012c000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18/libexec/src/net/http/transport.go:1929 +0x110
bufio.(*Reader).fill(0xc0000a8900)
	/usr/local/Cellar/go/1.18/libexec/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc0000a8900, 0x1)
	/usr/local/Cellar/go/1.18/libexec/src/bufio/bufio.go:144 +0xcc
net/http.(*persistConn).readLoop(0xc0002185a0)
	/usr/local/Cellar/go/1.18/libexec/src/net/http/transport.go:2093 +0x2bc
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.18/libexec/src/net/http/transport.go:1750 +0x24c5

 Goroutine 26 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0xc0002185a0)
	/usr/local/Cellar/go/1.18/libexec/src/net/http/transport.go:2392 +0x1a5
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.18/libexec/src/net/http/transport.go:1751 +0x2556
]
FAIL	github.com/jxsl13/amqpx/pool	4.930s
```

**Comment by JigarJoshi04** [comment]
Hey @jxsl13 ,
I can pick this up.
Need more context over this issue.
Also I want to ask if this would be a good issue for the beginners.

**Comment by jxsl13** [comment]
This is not a good first issue. It is fixed already but Session has a similar "problem". Which is not a problem but just a dangling goroutine that needs some time to be closed (some tcp network timeout). 
It is not exactly a leak.
